### ISSUE TITLE
Correct citation?

### ISSUE THREAD

**Issue by nilshg** [floswald/ApproXD.jl#7]
Now that I'm preparing my thesis for submission, I'd like to acknowledge the work of all the package developers that have helped me get my results. How do you want ApproXD.jl to be cited?

**Comment by floswald** [comment]
Hi Nils,

that is good news, congratulations! The citation is in the license file
(including a typo...), and it looks like this:

High Dimensional Function Approximation in Julia,
https://github.com/floswald/ApproXD.jl, Florian Oswald 2014 Thanks for
using/citing it!
florian

**Comment by nilshg** [comment]
Cool, will use this, thanks!
